# docker-compose.yml

version: '3.8'

services:
  backend:
    build: .
    container_name: starwars_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      