services:
  backend:
    build: .
    container_name: starwars_backend
    ports:
      - "6969:8000"
    volumes:
      - ./backend:/app/backend
      - ./cli:/app/cli
      - ./backend/logs:/app/backend/logs

  cli:
    build: .
    container_name: starwars_cli
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - backend
    volumes:
      - ./cli:/app/cli
